# Generated by Django 4.0.3 on 2022-03-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.URLField()),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_admitted_to_shelter', models.DateField()),
                ('is_spayed_or_neutered', models.BooleanField()),
                ('physical_description', models.TextField()),
                ('about_me', models.TextField()),
                ('is_adopted', models.BooleanField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
